### ISSUE TITLE
Functionality for Room,Join,Emit and Broadcast function

### ISSUE THREAD

**Issue by WhoAdarshPandya** [envis10n/deno-ws#1]
i come from node background where i used socket.io , in deno they provide std library and then your library , i request you to please add Room, Join,Emit,Broadcast functions, as i don't know how to implement all of that

Thanks :)

**Comment by envis10n** [comment]
Socket.io functionality is outside if the scope of this particular module.

The intent with deno_ws is to provide a slightly more node-like experience with event emitters, over the slightly more complicated but performant method with the std ws module directly.
